services:
  app:
    build:
      context: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - JAVA_OPTS=
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
